{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "plaza-devops-webapp.serviceAccountName" . }}
  labels:
    {{- include "plaza-devops-webapp.labels" . | nindent 4 }}
{{- end }}
